const {test}=require('node:test');const assert=require('node:assert/strict');const {resolve}=require('node:path');const {createLoader}=require('./csv-test-loader.cjs');
const project=resolve(process.env.CSV_PROJECT_ROOT||resolve(__dirname,'..'));let scenario,index=0,queries=[],navigation=[];
const query=(data,patch={})=>({data,isPending:false,isError:false,refetch:async()=>{},...patch});
const overrides={
 react:{...require('react'),useState:init=>[Object.hasOwn(scenario.state??{},index)?scenario.state[index++]:(index++,typeof init==='function'?init():init),()=>{}],useRef:v=>({current:v}),useEffect:()=>{}},
 'react-native':{ActivityIndicator:'Spinner',FlatList:'List',Modal:'Modal',Pressable:'Pressable',ScrollView:'ScrollView',Switch:'Switch',Text:'Text',TextInput:'Input',View:'View',StyleSheet:{create:v=>v},Platform:{OS:'android',select:o=>o.android??o.default}},
 'expo-router':{useRouter:()=>({canGoBack:()=>false,replace:p=>navigation.push(p),back:()=>navigation.push('back')})},
 'expo-sqlite':{useSQLiteContext:()=>({})},'@react-native-community/netinfo':{useNetInfo:()=>({isConnected:!scenario.offline,isInternetReachable:!scenario.offline})},
 '@/features/auth/auth-context':{useAuth:()=>({session:{user:{id:'alice'}}})},
 '@tanstack/react-query':{useQuery:o=>{queries.push(o);return scenario[o.queryKey[1]]??query(undefined);},useQueryClient:()=>({invalidateQueries:async()=>{}})},
 '@/components/ui/app-button':{AppButton:({label,...props})=>({type:'Button',props:{...props,label,children:label}})},
 '@/offline/sync/sync-refresh':{useRefreshLocalFinance:()=>({isPending:false,mutateAsync:async()=>{}})},
 '@/offline/sync/queue-health':{useRetryQueuedMutations:()=>({isPending:false,mutateAsync:async()=>{}})},
 '@/features/csv/csv-files':{clearCSVFiles:()=>{},pickCSV:async()=>null,exportCSV:async()=>0},'@/features/csv/csv-service':{},'@/features/csv/csv-sync':{},
};
for(const[n,v]of Object.entries(overrides))if(n.startsWith('@/'))overrides[resolve(project,'src',n.slice(2)+'.ts')]=v;
const screen=createLoader(project,overrides)('features/csv/csv-screen.tsx');
function render(patch={}){scenario={'csv-options':query({accounts:[{id:'a',name:'Wallet',currency_code:'USD',currency_minor_unit:2}],categories:[]}), 'csv-history':query([]),'csv-report':query([]),state:{},...patch};index=0;queries=[];navigation=[];const nodes=[];function visit(n){if(n==null||typeof n==='boolean')return;if(Array.isArray(n)){n.forEach(visit);return;}if(typeof n==='string'||typeof n==='number'){nodes.push(String(n));return;}if(typeof n.type==='function'){visit(n.type(n.props));return;}nodes.push(n);visit(n.props?.children);}visit(screen.CSVScreen());return {text:nodes.filter(n=>typeof n==='string').join(' ').replace(/\s+/g,' '),buttons:nodes.filter(n=>n.type==='Button'),queries};}
test('empty tools show export actions and clear empty history',()=>{const r=render();assert.match(r.text,/CSV import & export/);assert.match(r.text,/No imports yet/);for(const name of ['Export transactions','Export accounts & balances','Choose CSV file'])assert.ok(r.buttons.some(b=>b.props.label===name));});
test('offline screen preserves exports and disables server actions',()=>{const r=render({offline:true});assert.match(r.text,/Offline/);assert.equal(r.buttons.find(b=>b.props.label==='Sync pending rows').props.disabled,true);assert.equal(r.buttons.find(b=>b.props.label==='Export transactions').props.disabled,false);});
test('loading/error states prevent import and provide reference retry',()=>{let r=render({'csv-options':query(undefined,{isPending:true})});assert.equal(r.buttons.find(b=>b.props.label==='Choose CSV file').props.disabled,true);r=render({'csv-options':query(undefined,{isError:true})});assert.match(r.text,/could not load/);assert.ok(r.buttons.some(b=>b.props.label==='Retry loading'));});
test('preview separates ready, invalid and duplicate records before confirmation',()=>{const r=render({state:{6:[{row:2,status:'ready',reason:'Validated'},{row:3,status:'invalid',reason:'Invalid date'},{row:4,status:'duplicate',reason:'Repeated'}]}});assert.match(r.text,/1 ready · 1 invalid · 1 duplicates/);assert.match(r.text,/Record 3 · invalid/);assert.ok(r.buttons.some(b=>b.props.label==='Import 1 valid rows'));});
test('saved partial report offers resume and per-record failure details',()=>{const r=render({state:{7:'batch'},'csv-history':query([{id:'batch',name:'bank.csv',created_at:'2026-09-30T06:00:00Z',total:3,ready:1,pending:0,imported:1,failed:1,duplicate:0,invalid:0}]),'csv-report':query([{row_number:2,status:'imported',reason:'Confirmed'},{row_number:3,status:'ready',reason:'Awaiting resume'},{row_number:4,status:'failed',reason:'Network unavailable'}])});assert.match(r.text,/1 confirmed/);assert.match(r.text,/Network unavailable/);assert.ok(r.buttons.some(b=>b.props.label==='Resume remaining ready rows'));assert.ok(r.buttons.some(b=>b.props.label==='Export import report'));});
test('local queries always execute offline and use user-specific keys',()=>{const r=render({offline:true,state:{7:'batch'}});assert.ok(r.queries.every(q=>q.networkMode==='always'));assert.ok(r.queries.every(q=>q.queryKey.includes('alice')));});
test('separator can be selected before picking a quoted semicolon file',()=>{const r=render();assert.ok(r.text.indexOf('Separator')<r.text.indexOf('Choose CSV file'));});
test('explicit back button returns to Plan when no stack history exists',()=>{const r=render();r.buttons.find(b=>b.props.label==='Back to Plan').props.onPress();assert.deepEqual(navigation,['/plan']);});
