const {test}=require('node:test');const assert=require('node:assert/strict');const {resolve}=require('node:path');const fs=require('node:fs');const ts=require('typescript');
const {createLoader}=require('./security-test-loader.cjs');const project=resolve(process.env.SECURITY_PROJECT_ROOT||resolve(__dirname,'..'));
function loader(overrides){for(const [key,value] of Object.entries(overrides))if(key.startsWith('@/')){overrides[resolve(project,'src',key.slice(2)+'.ts')]=value;overrides[resolve(project,'src',key.slice(2)+'.tsx')]=value;}return createLoader(project,overrides);}
function nodes(node,out=[]){if(Array.isArray(node)){node.forEach(n=>nodes(n,out));return out;}if(node&&typeof node==='object'){out.push(node);nodes(node.props?.children,out);}return out;}
function boundary(privacy,path){let route;const overrides={'react-native':{View:'View',Text:'Text',StyleSheet:{create:v=>v}},'expo-router':{usePathname:()=>path,useRouter:()=>({replace:p=>route=p})},'@/components/ui/app-button':{AppButton:'Button'},'@/features/security/security-provider':{useSecurity:()=>({config:{privacy}})},'@/design/tokens':{colors:{background:'white',text:'black'}}};const mod=loader(overrides)('features/security/privacy-boundary.tsx');return {tree:mod.PrivacyBoundary({children:'SENSITIVE FINANCIAL CHILD'}),get route(){return route;}};}
test('privacy blocks interaction, hides descendants from accessibility, and covers all financial routes',()=>{for(const path of ['/home','/accounts','/activity','/debt-dashboard','/csv-tools','/transaction-detail','/notifications','/settings']){const f=boundary(true,path),views=nodes(f.tree).filter(n=>n.type==='View');const hidden=views.find(n=>n.props.accessibilityElementsHidden===true);assert.ok(hidden,path);assert.equal(hidden.props.pointerEvents,'none');assert.equal(hidden.props.importantForAccessibility,'no-hide-descendants');assert.ok(hidden.props.style.some(s=>s?.opacity===0));assert.equal(nodes(f.tree).filter(n=>n.type==='Button').length,1);}});
test('security settings remain available in privacy mode',()=>{const f=boundary(true,'/security');assert.equal(nodes(f.tree).find(n=>n.props.importantForAccessibility)?.props.accessibilityElementsHidden,false);assert.equal(nodes(f.tree).filter(n=>n.type==='Button').length,0);});
test('privacy off exposes the normal workspace',()=>{const f=boundary(false,'/accounts');assert.equal(nodes(f.tree).find(n=>n.props.importantForAccessibility)?.props.pointerEvents,'auto');});
test('privacy cover can navigate to settings without unmounting the router',()=>{const f=boundary(true,'/home');nodes(f.tree).find(n=>n.type==='Button').props.onPress();assert.equal(f.route,'/security');assert.ok(nodes(f.tree).some(n=>n.props.children==='SENSITIVE FINANCIAL CHILD'));});
test('remote push payload uses generic text regardless of sensitive notification contents',()=>{const path=resolve(project,'supabase/functions/notification-dispatch/index.ts'),source=fs.readFileSync(path,'utf8'),ast=ts.createSourceFile(path,source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);let expression;function walk(node){if(ts.isVariableDeclaration(node)&&node.name.getText(ast)==='messages'&&node.initializer?.getText(ast).includes('devices.map'))expression=node.initializer.getText(ast);ts.forEachChild(node,walk);}walk(ast);assert.ok(expression);const js=ts.transpileModule(expression,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText.replace(/^"use strict";\s*/, '');const fn=new Function('devices','notification','notificationId','return '+js);const results=fn([{expo_push_token:'ExponentPushToken[device]'}],{title:'Account USD 125,000',body:'Merchant and secret notes',deep_link:'/transaction-detail'},'id');assert.equal(results[0].title,'Finance Coach');assert.equal(results[0].body,'You have a new notification. Open Finance Coach to view it.');assert.ok(!JSON.stringify(results).includes('125,000'));assert.ok(!JSON.stringify(results).includes('secret notes'));assert.equal(results[0].data.notificationId,'id');});
test('foreground notification handler suppresses sensitive OS banners and lists',async()=>{let handler;const mod=loader({'expo-notifications':{setNotificationHandler:h=>handler=h},'expo-router':{},'@tanstack/react-query':{},'@/features/notifications/notification-client':{},'@/features/notifications/notification-query':{},'@/features/notifications/notification-service':{}});mod('features/notifications/notification-runtime.tsx');const response=await handler.handleNotification();assert.equal(response.shouldShowBanner,false);assert.equal(response.shouldShowList,false);assert.equal(response.shouldPlaySound,false);});
test('Android reminder channel protects lock-screen visibility',async()=>{let options;const overrides={'react-native':{Platform:{OS:'android'}},'expo-constants':{},'expo-device':{},'expo-crypto':{},'expo-secure-store':{},'expo-notifications':{AndroidImportance:{DEFAULT:3},AndroidNotificationVisibility:{SECRET:-1},setNotificationChannelAsync:async(id,v)=>{assert.equal(id,'finance-coach-reminders');options=v;}},'@/features/notifications/notification-service':{}};const mod=loader(overrides)('features/notifications/notification-client.ts');await mod.ensureFinanceCoachNotificationChannel();assert.equal(options.lockscreenVisibility,-1);});
