const {test}=require('node:test');const assert=require('node:assert/strict');const {resolve}=require('node:path');const React=require('react');
const project=resolve(process.env.SECURITY_PROJECT_ROOT||resolve(__dirname,'..'));
const {createLoader}=require('./security-test-loader.cjs');
const base={version:1,enabled:true,biometric:false,privacy:false,timeout:0,pepper:'a'.repeat(64),pinHash:'b'.repeat(64),recoveryHash:'c'.repeat(64),failures:0,blockedUntil:0};
function nodes(node,out=[]){if(Array.isArray(node)){node.forEach(v=>nodes(v,out));return out;}if(node&&typeof node==='object'){out.push(node);nodes(node.props?.children,out);}return out;}
function contains(node){if(node==='SENSITIVE FINANCIAL CHILD')return true;if(Array.isArray(node))return node.some(contains);return Boolean(node&&typeof node==='object'&&contains(node.props?.children));}
function text(node){return nodes(node).filter(n=>n.type==='Text').map(n=>Array.isArray(n.props.children)?n.props.children.join(''):String(n.props.children??'')).join(' ');}
async function fixture(options={}){
 let slots=[],index=0,effects=[],cleanups=[],tree,listeners={},resolvePIN,resolveBio;
 let config={...base,...options.config},failLoad=options.failLoad,protectedCalls=0,hardware=options.hardware??true,enrolled=options.enrolled??true,bioSuccess=options.bioSuccess??true,unlockCalls=0;
 const app={currentState:'active',addEventListener:(name,fn)=>{listeners[name]=fn;return {remove:()=>delete listeners[name]};}};
 const useState=initial=>{const at=index++;if(!(at in slots))slots[at]=typeof initial==='function'?initial():initial;return [slots[at],v=>{slots[at]=typeof v==='function'?v(slots[at]):v;}];};
 const useRef=initial=>{const at=index++;return slots[at]??(slots[at]={current:initial});};
 const useEffect=(fn,deps)=>{const at=index++;const previous=slots[at];if(!previous||deps.some((v,i)=>v!==previous[i])){slots[at]=deps;effects.push(fn);}};
 const overrides={react:{...React,useState,useRef,useEffect,useCallback:(fn,deps)=>{const at=index++;if(!slots[at]||deps.some((v,i)=>v!==slots[at].deps[i]))slots[at]={fn,deps};return slots[at].fn;}},
 'react-native':{AppState:app,Platform:{OS:'android'},StyleSheet:{create:v=>v},View:'View',Text:'Text',TextInput:'Input',ActivityIndicator:'Spinner'},
 '@/features/auth/auth-context':{useAuth:()=>({session:{user:{id:'alice'}}})},'@/components/ui/app-button':{AppButton:'Button'},'@/design/tokens':{colors:{background:'white',text:'black',border:'grey',danger:'red'}},
 'expo-screen-capture':{preventScreenCaptureAsync:async()=>{protectedCalls++;if(options.failProtection)throw Error('protection failed');},enableAppSwitcherProtectionAsync:async()=>{}},
 'expo-local-authentication':{hasHardwareAsync:async()=>hardware,isEnrolledAsync:async()=>enrolled,authenticateAsync:async params=>{assert.equal(params.disableDeviceFallback,true);assert.equal(params.biometricsSecurityLevel,'strong');if(options.deferredBio)return new Promise(r=>resolveBio=r);return {success:bioSuccess};}},
 '@/features/security/lock-service':{loadLock:async()=>{if(failLoad)throw Error('storage failed');return config;},unlockPIN:async(user,pin)=>{unlockCalls++;assert.equal(user,'alice');if(options.deferredPIN)return new Promise(r=>resolvePIN=r);if(pin!=='491827')throw Error('Incorrect credential');return config;},recoverPIN:async()=>({config,recovery:'NEW-RECOVERY-CODE'}),shouldAutoLock:(c,start,now)=>c.enabled&&(c.timeout===0||now-start>=c.timeout*1000)},
 };
 overrides[resolve(project,'src/features/security/lock-service.ts')]=overrides['@/features/security/lock-service'];
 const provider=createLoader(project,overrides)('features/security/security-provider.tsx');const element=provider.SecurityProvider({children:'SENSITIVE FINANCIAL CHILD'});
 function render(){index=0;tree=element.type(element.props);const pending=effects;effects=[];for(const fn of pending){const cleanup=fn();if(cleanup)cleanups.push(cleanup);}return tree;}
 async function settle(){await new Promise(r=>setImmediate(r));render();await new Promise(r=>setImmediate(r));return render();}
 render();await settle();
 return {render,settle,get tree(){return tree;},get protectedCalls(){return protectedCalls;},get unlockCalls(){return unlockCalls;},setInput:(label,value)=>{nodes(tree).find(n=>n.type==='Input'&&n.props.accessibilityLabel===label).props.onChangeText(value);render();},press:label=>{const n=nodes(tree).find(n=>n.type==='Button'&&n.props.label===label);assert.ok(n,'button '+label);n.props.onPress();render();},state:state=>{app.currentState=state;listeners.change(state);render();},event:name=>{listeners[name]?.();render();},resolvePIN:()=>resolvePIN(config),resolveBio:r=>resolveBio(r),setFailLoad:v=>failLoad=v,dispose:()=>cleanups.forEach(fn=>fn())};
}
const check=(name,opts,fn)=>test(name,async()=>{const f=await fixture(opts);try{await fn(f);}finally{f.dispose();}});
check('cold-start lock never mounts protected children and PIN input is secure',{},f=>{assert.match(text(f.tree),/locked/);assert.ok(!contains(f.tree));assert.equal(nodes(f.tree).find(n=>n.type==='Input').props.secureTextEntry,true);assert.equal(f.protectedCalls,1);});
check('disabled app lock still initializes native screen privacy before exposing children',{config:{enabled:false}},f=>{assert.ok(contains(f.tree));assert.equal(f.protectedCalls,1);});
check('correct PIN exposes children while incorrect PIN keeps the gate closed',{},async f=>{f.setInput('App PIN','111111');f.press('Unlock');await f.settle();assert.match(text(f.tree),/Incorrect/);f.setInput('App PIN','491827');f.press('Unlock');await f.settle();assert.ok(contains(f.tree));});
check('duplicate unlock taps cannot launch parallel attempts',{deferredPIN:true},async f=>{f.setInput('App PIN','491827');f.press('Unlock');await f.settle();f.press('Unlock');assert.equal(f.unlockCalls,1);f.resolvePIN();await f.settle();});
check('backgrounding during PIN verification invalidates the pending result',{deferredPIN:true},async f=>{f.setInput('App PIN','491827');f.press('Unlock');await f.settle();f.state('background');f.resolvePIN();await f.settle();f.state('active');assert.match(text(f.tree),/locked/);assert.ok(!contains(f.tree));});
check('inactive and Android notification shade cover the financial tree',{config:{enabled:false}},f=>{f.state('inactive');assert.ok(!contains(f.tree));f.state('active');f.event('blur');assert.ok(!contains(f.tree));f.event('focus');assert.ok(contains(f.tree));});
check('immediate background policy requires re-unlock after returning',{},async f=>{f.setInput('App PIN','491827');f.press('Unlock');await f.settle();f.state('background');f.state('active');assert.match(text(f.tree),/locked/);});
check('background grace timeout preserves an already unlocked session before expiry',{config:{timeout:60}},async f=>{f.setInput('App PIN','491827');f.press('Unlock');await f.settle();f.state('background');f.state('active');assert.ok(contains(f.tree));});
check('unavailable secure storage fails closed and explicit retry reinitializes',{failLoad:true},async f=>{assert.match(text(f.tree),/remain hidden/);assert.ok(!contains(f.tree));f.setFailLoad(false);f.press('Retry initialization');await f.settle();assert.match(text(f.tree),/locked/);});
check('native screen protection failure fails closed',{failProtection:true},f=>{assert.match(text(f.tree),/remain hidden/);assert.ok(!contains(f.tree));});
check('missing biometric hardware falls back to PIN without unlocking',{config:{biometric:true},hardware:false},async f=>{f.press('Unlock with biometrics');await f.settle();assert.match(text(f.tree),/Use your PIN/);assert.match(text(f.tree),/locked/);});
check('biometric cancellation leaves the gate closed',{config:{biometric:true},bioSuccess:false},async f=>{f.press('Unlock with biometrics');await f.settle();assert.match(text(f.tree),/cancelled/);assert.match(text(f.tree),/locked/);});
check('strong biometric success exposes the financial workspace',{config:{biometric:true}},async f=>{f.press('Unlock with biometrics');await f.settle();assert.ok(contains(f.tree));});
check('backgrounding cancels authorization from a delayed biometric success',{config:{biometric:true},deferredBio:true},async f=>{f.press('Unlock with biometrics');await f.settle();f.state('background');f.resolveBio({success:true});await f.settle();f.state('active');assert.match(text(f.tree),/locked/);});
check('recovery requires matching new PIN and shows replacement code before continuing',{},async f=>{f.press('Forgot PIN?');f.setInput('Recovery code','OLD-CODE');f.setInput('New PIN','817294');f.setInput('Confirm new PIN','000000');f.press('Reset PIN');await f.settle();assert.match(text(f.tree),/does not match/);f.setInput('Confirm new PIN','817294');f.press('Reset PIN');await f.settle();assert.match(text(f.tree),/NEW-RECOVERY-CODE/);assert.ok(!contains(f.tree));f.press('I saved my recovery code');await f.settle();assert.ok(contains(f.tree));});
check('foreground inactivity timer locks the workspace after the configured deadline',{config:{timeout:30}},async f=>{f.setInput('App PIN','491827');f.press('Unlock');await f.settle();assert.ok(contains(f.tree));const original=Date.now,now=original();Date.now=()=>now+31000;try{await new Promise(r=>setTimeout(r,1100));f.render();assert.match(text(f.tree),/locked/);assert.ok(!contains(f.tree));}finally{Date.now=original;}});
